name: Deployment in production

concurrency:
  group: production-deployment
  cancel-in-progress: false

on:
  workflow_dispatch:

  push:
    branches:
      - main
    paths:
      - 'flight_bundle/**'
      - '.github/workflows/**'

jobs:
  deploy:
    name: Deploy bundle
    runs-on: ubuntu-latest

    steps:
      # Récupère le dépôt
      - name: Checkout repository
        uses: actions/checkout@v4

      # Installe la Databricks CLI
      - name: Install Databricks CLI
        uses: databricks/setup-cli@main

      # Vérifie que le bundle est présent
      - name: Check bundle
        run: |
          pwd
          ls -la
          ls -la ./flight_bundle

      # Valide le bundle
      - name: Validate bundle
        working-directory: ./flight_bundle
        run: databricks bundle validate
        env:
          DATABRICKS_TOKEN: ${{ secrets.SP_TOKEN }}
          DATABRICKS_BUNDLE_ENV: prod

      # Déploie le bundle
      - name: Deploy bundle
        working-directory: ./flight_bundle
        run: databricks bundle deploy
        env:
          DATABRICKS_TOKEN: ${{ secrets.SP_TOKEN }}
          DATABRICKS_BUNDLE_ENV: prod
